@startuml FrontendPackage
title Frontend Package Overview

left to right direction
skinparam packageStyle rectangle
skinparam linetype ortho
skinparam shadowing false
skinparam ArrowColor #444444
skinparam ArrowFontSize 12
skinparam package {
  BorderColor #222222
  BackgroundColor #FFFFFF
  FontSize 16
}
skinparam defaultFontName Arial

package "Frontend" {
  package "auth" as auth
  package "services" as services
  package "pages" as pages
  package "components" as components
  package "node_modules" as node_modules
  package "utils" as utils

  auth -[hidden]-> services
  services -[hidden]-> pages
  components -[hidden]-> node_modules
  node_modules -[hidden]-> utils
  auth -[hidden]-> components
  services -[hidden]-> node_modules
  pages -[hidden]-> utils
}

pages ..> components : <<import>>
pages ..> services : <<import>>
pages ..> utils : <<import>>

auth ..> services : <<import>>
auth ..> utils : <<import>>

components ..> services : <<import>>
components ..> utils : <<import>>

services ..> utils : <<import>>
services ..> node_modules : <<import>>

utils ..> node_modules : <<import>>

@enduml
